### PR TITLE
BUGFIX: adding zip hack to @propelleraero/cesium

### PR DESCRIPTION
**Pull request by madole**

### CODE REVIEW

**Comment by chris-cooper** [comment]
Is it straightforward to reset the whitespace on this to minimise the diff?

**Comment by madole** [comment]
Adding `?w=1` to the diff url will ignore most of the whitespace it can

**Comment by chris-cooper** [comment]
Yes I tried that but it was still messy. It's not a big deal as this file is unlikely to change often.

**Comment by katSchmid** [comment]
I am getting back at this.
Do we think this approach is working or were there more problems?

**Comment by chris-cooper** [comment]
Closing this PR as it's very old and not holding us up.

**Pull request closed without merging**
