### PR TITLE
V1.99

### PR DESCRIPTION
**Pull request by katSchmid**

### CODE REVIEW

**Comment by katSchmid** [comment]
image

**Comment by chris-cooper** [comment]
Shouldn't there be a single commit at the top after `e7987bbcf8459648f0003c45802d0734b23f4f54` ([last commit of 1.99](https://github.com/CesiumGS/cesium/commits/1.99)) with all the Propeller modifications as per https://github.com/PropellerAero/cesium/blob/main/README-PROPELLER.md ?

**Comment by chris-cooper** [comment]
Ah it looks like it's across two commits with the changes here:

https://github.com/PropellerAero/cesium/compare/e7987bbcf8459648f0003c45802d0734b23f4f54...483f5b40bbaaee642e82aa0742afb89068ebcf43

**Comment by chris-cooper** [comment]
I think this file is legacy and should be removed [gulpfile.cjs](https://github.com/PropellerAero/cesium/compare/e7987bbcf8459648f0003c45802d0734b23f4f54...483f5b40bbaaee642e82aa0742afb89068ebcf43#diff-ba119e2e4e0b714d1f47efb72723cfa2b17d614e75897d8d2fe44e018cb23ddf)

**Comment by katSchmid** [comment]
I had to unhack Model stuff, i can squash them?

**Comment by chris-cooper** [comment]
Yes you can squash all our changes.  At the moment this branch seems to be back at the upstream 1.99 
image

**Comment by katSchmid** [comment]
I broke the history while rewriting it have to do redo

**Pull request closed without merging**
